# Generated by Django 4.1.5 on 2023-02-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_product_pirce_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
